#!/bin/sh
unset SESSION_MANAGER
exec openbox-session &
source ${HOME}/.xprofile &
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export GLFW_IM_MODULE=ibus
fcitx5 &
dbus-launch --exit-with-session ${HOME}/.config/openbox/autostart &
